### PR TITLE
improve modules to use new project structures

### PR DESCRIPTION
**Pull request by kilip**
This pull requests will make Orders module to be compatible with new project structure (ref cross-solution/YAWIK#466)

### CODE REVIEW

**Comment by cbleek** [comment]
Hi kilip,

I've updated my local env and get a  `'Module (Orders) could not be initialized.'` because the Module.php was moved into the `src/` directory. What do I have to do, if I want to update the Orders Module within an old-structured yawik installation?

**Comment by cbleek** [comment]
I assume, I have to update the module via:

`cbleek@xenon:/home/cbleek/Projects/YAWIK# ./composer.phar require yawik/orders:dev-master`

But this will only work after merging this PR, right?

**Comment by cbleek** [comment]
we'll just try it

**Comment by kilip** [comment]
Yes @cbleek, you need to merge this pull request first. Do you still have error?

**Comment by cbleek** [comment]
yes, if I `git clone` the develop branch into the `module/` directory, I stll get the 'Module (Orders) could not be initialized.' exception.

If I try to `./composer.phar require yawik/orders:dev-develop`

```
YAWIK# ./composer.phar require yawik/orders:dev-develop
...
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for yawik/orders dev-develop -> satisfiable by yawik/orders[dev-develop].
    - yawik/orders dev-develop requires yawik/core ^0.32@dev -> satisfiable by yawik/core[0.32.x-dev] but these conflict with your requirements or minimum-stability.
```

**Comment by kilip** [comment]
We do not have any stable release yet for this module.

I assume your yawik apps using ```cross-solution/YAWIK``` repository. Please add this line into your ```composer.json```:
```json
"prefer-stable": true,
"minimum-stability": "dev",
"replace": {
        "yawik/applications": "self.version",
        "yawik/auth": "self.version",
        "yawik/core": "self.version",
        "yawik/cv": "self.version",
        "yawik/geo": "self.version",
        "yawik/install": "self.version",
        "yawik/jobs": "self.version",
        "yawik/organizations": "self.version",
        "yawik/pdf": "self.version",
        "yawik/settings": "self.version"
}
```
The ```replace``` section will tell composer that all required module (applications, jobs, cv, etc.) already installed.

I have change this on my own [repo](https://github.com/kilip/yawik/blob/develop/composer.json). I will make a pull when I think there are no errors/bugs left.

**Comment by cbleek** [comment]
I'm getting now: 

```
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for yawik/test dev-master -> satisfiable by yawik/test[dev-master].
    - yawik/orders dev-develop requires yawik/core ^0.32@dev -> satisfiable by yawik/core[0.32.x-dev].
    - don't install yawik/core 0.32.x-dev|remove yawik/test dev-master
    - Installation request for yawik/orders dev-develop -> satisfiable by yawik/orders[dev-develop].
```

**Comment by kilip** [comment]
Can you share your composer.json file?

**Comment by cbleek** [comment]
```
cbleek@xenon:~/Projects/YAWIK$ git diff composer.json
diff --git a/composer.json b/composer.json
index 28ffe16..1f527b1 100644
--- a/composer.json
+++ b/composer.json
@@ -81,6 +81,20 @@
         "behat/mink-extension": "^2.3",
         "novaway/common-contexts": "~2.0"
     },
+    "prefer-stable": true,
+    "minimum-stability": "dev",
+    "replace": {
+        "yawik/applications": "self.version",
+        "yawik/auth": "self.version",
+        "yawik/core": "self.version",
+        "yawik/cv": "self.version",
+        "yawik/geo": "self.version",
+        "yawik/install": "self.version",
+        "yawik/jobs": "self.version",
+        "yawik/organizations": "self.version",
+        "yawik/pdf": "self.version",
+        "yawik/settings": "self.version"
+    },
     "scripts": {
         "post-install-cmd": [
             "chmod +x ./install.sh && ./install.sh"
```

[composer.txt](https://github.com/yawik/Orders/files/2505675/composer.txt)

**Comment by kilip** [comment]
I hope this works now, add this line into your composer config:
```json
    "extra": {
        "branch-alias": {
            "dev-develop": "0.32-dev"
        }
    }
```

**Comment by kilip** [comment]
@cbleek finally this config is working in my composer.json:
```json
    "extra": {
        "branch-alias": {
            "dev-develop": "0.33-dev",
            "dev-master": "0.32-dev"
        }
    }
```

**Comment by cbleek** [comment]
yes, after adding `"dev-master": "0.32-dev"` I was able to

```
cbleek@xenon:~/Projects/YAWIK$ ./composer.phar require yawik/orders:dev-develop
./composer.json has been updated
...
  - Installing yawik/orders (dev-develop d4d9cb4): Cloning d4d9cb446b

```
But the module was installed in vendor/yawik/orders and not in module/Orders. Which leads to the problem, that a JS file cannot be loaded.

auswahl_463

**Comment by kilip** [comment]
@cbleek i have push directly a new change in develop, that should be fix script loading issues. But I think the error will be raised again, because I need to merge my yawik repo into cross-solution/YAWIK .

I forget to tell you, now we can develop this module outside Yawik repository. Please follow development guide in this page:

https://github.com/yawik/Orders/tree/develop#development

**Pull request merged**
